name: Node.js CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }} 
          port: ${{ secrets.PORT }}

          # Skrip dibungkus dengan jel_exec agar berjalan di node yang benar
          script: |
            jel_exec --nodeId 61715 << 'EOL'
              cd /home/jelastic/ROOT
              git pull origin master
              echo "--- Git status after pull ---"
              git status
              echo "--- Installing dependencies ---"
              npm ci --omit=dev
              echo "--- Building application ---"
              npm run build
              echo "--- Restarting PM2 application ---"
              pm2 restart my-app
            EOL