name: Node.js CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Deployment via Jelastic API
        env:
          JELASTIC_API_HOST: app.jkt01.dewaweb.com
          JELASTIC_TOKEN: ${{ secrets.JELASTIC_TOKEN }}
          ENV_NAME: ${{ secrets.ENV_NAME }}
          NODE_ID: 61715

        run: |
          COMMANDS_TO_RUN="cd /home/jelastic/ROOT && git pull origin master && npm ci && npm run build && pm2 restart my-app"

          echo "Executing remote commands using Access Token..."

          API_RESPONSE=$(curl -s "https://${JELASTIC_API_HOST}/1.0/environment/control/execmdbyid" --data-urlencode "token=${JELASTIC_TOKEN}" --data-urlencode "envname=${ENV_NAME}" --data-urlencode "nodeid=${NODE_ID}" --data-urlencode "command=${COMMANDS_TO_RUN}")

          echo "API Response: $API_RESPONSE"

          RESULT_CODE=$(echo $API_RESPONSE | jq -r .result)
          if [ "$RESULT_CODE" != "0" ]; then
            echo "::error::Command execution failed. See response above."
            exit 1
          fi

          echo "✅ Deployment commands executed successfully via API."