name: Node.js CD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }} 
          port: ${{ secrets.PORT }}

          # Skrip diubah menjadi satu baris dengan && untuk eksekusi yang andal
          script: |
            jel_exec --nodeId 61715 "cd /home/jelastic/ROOT && git pull origin master && npm ci && npm run build && pm2 restart my-app"